sudo: required
services:
  - docker

before_install:
  # Build and run tests using Docker Compose
  - docker-compose build
  - docker-compose up --abort-on-container-exit --exit-code-from automation

script:
  # Add additional script commands if needed

after_success:
  # Build and push Docker images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push roeezach/expenser-backend
  - docker push roeezach/expenser-frontend
