name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run tests using Docker Compose
        run: |
          docker-compose build
          docker-compose up --abort-on-container-exit --exit-code-from automation

      - name: Push Docker images to Docker Hub
        if: success()
        run: |
          docker-compose push
          docker push roeezach/expenser-backend
          docker push roeezach/expenser-frontend
          docker push roeezach/expenser-be-tests
